format = """
$all
$env_var$character"""

[env_var.SQUAREBOX]
format = "[🟧📦](yellow) "

[container]
disabled = true

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
